POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NGE2OTA1NGFiNmZhYmFiYzBlM2M5MTUiLCJpYXQiOjE2ODk0MDI2MjgsImV4cCI6MTY4OTQwNjIyOH0.5_dTfCdt73KDc9MAL8BENftcAjJR-83bkhNRkrYz08s

{
    "title": "Swizec Teller's Blog",
    "author": "Swizec Teller",
    "url": "https://swizec.com/blog/",
    "likes": 1000
}